### ISSUE TITLE
遇到的一些问题和解决方法

### ISSUE THREAD

**Issue by Joker-zou** [wangliyang206/BeanSproutAssistantAndroid#2]
1.遇到java.nio.file.InvalidPathException，Illegal char ＜:＞ at index报错，删掉app下build.gradle有"豆芽助手"那一块的东西就好
2.同时会打开两个软件的问题，跳过splashactivity即可
3.某些软件下滑上划不流畅，无法滑动的问题，在AutoTouchService的onSlide方法中，增加路径的offset到1000，增加duration到100会好很多

东西很不错

**Comment by wangliyang206** [comment]
谢谢您的反馈，为了项目有更好的体验我会认真采纳，后期会持续维护，期待您的继续关注。
